/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author bakti
 */
import controller.controllerCariBarang;


import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FormCariBarang extends javax.swing.JFrame {

    private JTextField txtSearch;
    private JButton btnSearch;
    private JButton btnKeluar;
    private JTable table;
    private controllerCariBarang controller;

    public FormCariBarang() {
        setTitle("Form Pencarian Barang");
        setSize(800, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);

        txtSearch = new JTextField();
        txtSearch.setBounds(20, 20, 200, 25);
        add(txtSearch);

        btnSearch = new JButton("Cari");
        btnSearch.setBounds(230, 20, 80, 25);
        add(btnSearch);

//        btnKeluar = new JButton("Keluar");
//        btnKeluar.setBounds(320, 20, 80, 25);
//        add(btnKeluar);
        
        String[] columnNames = {"ID", "Kode", "Nama Barang", "Jumlah", "Harga", "Merek"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
        table = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setBounds(20, 60, 750, 300);
        add(scrollPane);

        controller = new controllerCariBarang(this);

        btnSearch.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.searchBarang();
            }
        });
        
//        btnKeluar.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                controller.keluar();
//            }
//        });
// 
        controller.loadBarang();
    }

    public JTextField getTxtSearch() {
        return txtSearch;
    }

    public JTable getTable() {
        return table;
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new FormCariBarang().setVisible(true));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
